fix JF

diff --git a/openvidu-test-e2e/jenkins/Jenkinsfile b/openvidu-test-e2e/jenkins/Jenkinsfile
--- a/openvidu-test-e2e/jenkins/Jenkinsfile
+++ b/openvidu-test-e2e/jenkins/Jenkinsfile
@@ -42,57 +42,59 @@ node('elastest') {
               sudo apt-get update && sudo apt-get --yes -o Dpkg::Options::="--force-confnew" install kurento-media-server
             fi
         '''.stripIndent())
-        }
-        stage('OpenVidu parent build') {
-          sh 'cd openvidu/openvidu-java-client && mvn --batch-mode versions:set -DnewVersion=1.0.0-TEST'
-          sh 'cd openvidu && mvn --batch-mode versions:set-property -Dproperty=version.openvidu.java.client -DnewVersion=1.0.0-TEST'
-          sh 'cd openvidu && mvn --batch-mode -DskipTests=true clean install'
-        }
-        stage('OpenVidu Browser build') {
-          sh 'cd openvidu/openvidu-browser && npm install --unsafe-perm && npm run build && npm link'
-        }
-        stage('OpenVidu Node Client build') {
-          sh 'cd openvidu/openvidu-node-client && npm install --unsafe-perm && npm run build && npm link'
-        }
-        stage('OpenVidu TestApp build') {
-          sh 'cd openvidu/openvidu-testapp && npm install --unsafe-perm && npm link openvidu-browser && npm link openvidu-node-client && export NG_CLI_ANALYTICS=ci && ./node_modules/@angular/cli/bin/ng build --prod'
-        }
-        stage('OpenVidu Server build') {
-          sh 'cd openvidu/openvidu-server/src/dashboard && npm install --unsafe-perm && npm link openvidu-browser && export NG_CLI_ANALYTICS=ci && ./node_modules/@angular/cli/bin/ng build --prod --output-path ../main/resources/static'
-          sh 'cd openvidu/openvidu-server && mvn --batch-mode clean compile package'
-        }
-        stage ('Environment Launch') {
-          sh 'openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -subj "/CN=www.mydom.com/O=My Company LTD./C=US" -keyout openvidu/openvidu-testapp/dist/key.pem -out openvidu/openvidu-testapp/dist/cert.pem'  
-          sh 'cd openvidu/openvidu-testapp/dist && http-server -S -p 4200 &> /testapp.log &'
-          sh '/usr/bin/kurento-media-server &> /kms.log &'
-          sh 'until $(curl --insecure --output /dev/null --silent http://127.0.0.1:8888/kurento); do echo "Waiting for KMS..."; sleep 1; done'
-          sh(script: '''#!/bin/bash
-            if [ "$DOCKER_RECORDING_VERSION" != "default" ]; then
-              echo "Using custom openvidu-recording tag: $DOCKER_RECORDING_VERSION"
-              cd openvidu/openvidu-server/target && java -jar -Dopenvidu.publicurl=https://172.17.0.1:4443/ -Dopenvidu.recording=true -Dopenvidu.recording.version=$DOCKER_RECORDING_VERSION -Dopenvidu.webhook=true -Dopenvidu.webhook.endpoint=http://127.0.0.1:7777/webhook openvidu-server-*.jar &> openvidu-server.log &
-            else
-              echo "Using default openvidu-recording tag"
-              cd openvidu/openvidu-server/target && java -jar -Dopenvidu.publicurl=https://172.17.0.1:4443/ -Dopenvidu.recording=true -Dopenvidu.webhook=true -Dopenvidu.webhook.endpoint=http://127.0.0.1:7777/webhook openvidu-server-*.jar &> openvidu-server.log &
-            fi
-          '''.stripIndent())
-          sh 'until $(curl --insecure --output /dev/null --silent --head --fail https://OPENVIDUAPP:MY_SECRET@localhost:4443/); do echo "Waiting for openvidu-server..."; sleep 2; done'
-        }
-        stage ('E2E tests') {
-          try {
-          	withEnv(['ET_SUT_HOST=' + sutIp]) {         
-	            sh(script: '''#!/bin/bash
-	              cd openvidu/openvidu-test-e2e && sudo mvn --batch-mode -DAPP_URL=https://${ET_SUT_HOST}:4200/ -DOPENVIDU_URL=https://${ET_SUT_HOST}:4443/ -DREMOTE_URL_CHROME=${ET_EUS_API} -DREMOTE_URL_FIREFOX=${ET_EUS_API} test
-	              if [[ "$?" -ne 0 ]] ; then
-	                echo "ERROR RUNNING TESTS"
-	                cat openvidu/openvidu-server/target/openvidu-server.log
-	              fi
-	            '''.stripIndent())
-            }
-          }
-          finally {
-            junit 'openvidu/openvidu-test-e2e/**/target/surefire-reports/TEST-*.xml'
-            archiveArtifacts artifacts: '**/openvidu-server.log'
-          }
+        
+        	withEnv(['ET_SUT_HOST=' + sutIp]) {
+        
+	            stage('OpenVidu parent build') {
+		          sh 'cd openvidu/openvidu-java-client && mvn --batch-mode versions:set -DnewVersion=1.0.0-TEST'
+		          sh 'cd openvidu && mvn --batch-mode versions:set-property -Dproperty=version.openvidu.java.client -DnewVersion=1.0.0-TEST'
+		          sh 'cd openvidu && mvn --batch-mode -DskipTests=true clean install'
+		        }
+		        stage('OpenVidu Browser build') {
+		          sh 'cd openvidu/openvidu-browser && npm install --unsafe-perm && npm run build && npm link'
+		        }
+		        stage('OpenVidu Node Client build') {
+		          sh 'cd openvidu/openvidu-node-client && npm install --unsafe-perm && npm run build && npm link'
+		        }
+		        stage('OpenVidu TestApp build') {
+		          sh 'cd openvidu/openvidu-testapp && npm install --unsafe-perm && npm link openvidu-browser && npm link openvidu-node-client && export NG_CLI_ANALYTICS=ci && ./node_modules/@angular/cli/bin/ng build --prod'
+		        }
+		        stage('OpenVidu Server build') {
+		          sh 'cd openvidu/openvidu-server/src/dashboard && npm install --unsafe-perm && npm link openvidu-browser && export NG_CLI_ANALYTICS=ci && ./node_modules/@angular/cli/bin/ng build --prod --output-path ../main/resources/static'
+		          sh 'cd openvidu/openvidu-server && mvn --batch-mode clean compile package'
+		        }
+		        stage ('Environment Launch') {
+		          sh 'openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -subj "/CN=www.mydom.com/O=My Company LTD./C=US" -keyout openvidu/openvidu-testapp/dist/key.pem -out openvidu/openvidu-testapp/dist/cert.pem'  
+		          sh 'cd openvidu/openvidu-testapp/dist && http-server -S -p 4200 &> /testapp.log &'
+		          sh '/usr/bin/kurento-media-server &> /kms.log &'
+		          sh 'until $(curl --insecure --output /dev/null --silent http://127.0.0.1:8888/kurento); do echo "Waiting for KMS..."; sleep 1; done'
+		          sh(script: '''#!/bin/bash
+		            if [ "$DOCKER_RECORDING_VERSION" != "default" ]; then
+		              echo "Using custom openvidu-recording tag: $DOCKER_RECORDING_VERSION"
+		              cd openvidu/openvidu-server/target && java -jar -Dopenvidu.publicurl=https://${ET_SUT_HOST}:4443/ -Dopenvidu.recording=true -Dopenvidu.recording.version=$DOCKER_RECORDING_VERSION -Dopenvidu.webhook=true -Dopenvidu.webhook.endpoint=http://127.0.0.1:7777/webhook openvidu-server-*.jar &> openvidu-server.log &
+		            else
+		              echo "Using default openvidu-recording tag"
+		              cd openvidu/openvidu-server/target && java -jar -Dopenvidu.publicurl=https://${ET_SUT_HOST}:4443/ -Dopenvidu.recording=true -Dopenvidu.webhook=true -Dopenvidu.webhook.endpoint=http://127.0.0.1:7777/webhook openvidu-server-*.jar &> openvidu-server.log &
+		            fi
+		          '''.stripIndent())
+		          sh 'until $(curl --insecure --output /dev/null --silent --head --fail https://OPENVIDUAPP:MY_SECRET@localhost:4443/); do echo "Waiting for openvidu-server..."; sleep 2; done'
+		        }
+		        stage ('E2E tests') {
+		          try {     
+		            sh(script: '''#!/bin/bash
+		              cd openvidu/openvidu-test-e2e && sudo mvn --batch-mode -DAPP_URL=https://${ET_SUT_HOST}:4200/ -DOPENVIDU_URL=https://${ET_SUT_HOST}:4443/ -DREMOTE_URL_CHROME=${ET_EUS_API} -DREMOTE_URL_FIREFOX=${ET_EUS_API} test
+		              if [[ "$?" -ne 0 ]] ; then
+		                echo "ERROR RUNNING TESTS"
+		                cat openvidu/openvidu-server/target/openvidu-server.log
+		              fi
+		            '''.stripIndent())
+		          }
+		          finally {
+		            junit 'openvidu/openvidu-test-e2e/**/target/surefire-reports/TEST-*.xml'
+		            archiveArtifacts artifacts: '**/openvidu-server.log'
+		          }
+		        }
+	        }
         }
       }
   }
